DROP TABLE IF EXISTS pantheon.designation_mappings;

CREATE TABLE pantheon.designation_mappings (
  taxon_designation_id integer NOT NULL PRIMARY KEY,
  abbreviation varchar NOT NULL,
  output_label varchar NOT NULL,
  mapping_class varchar NOT NULL
);

INSERT INTO pantheon.designation_mappings
VALUES
('304', 'RedList_GB_Pre94-Insu', '[Threat]', 'IUCN Threat listing'),
('314', 'RedList_pre94-Insu', '[Threat]', 'IUCN Threat listing'),
('354', 'BAP-1997', 'BAP', 'Legal listing'),
('356', 'BAP-Middle', 'BAP', 'Legal listing'),
('358', 'BAP-2007', 'BAP', 'Legal listing'),
('377', 'England_NERC_S.41', 'S41. Priority Species', 'Legal listing'),
('382', 'Legal Protection', 'Legal protection', 'Legal listing'),
('383', 'Legal Protection', 'Legal protection', 'Legal listing'),
('384', 'Legal Protection', 'Legal protection', 'Legal listing'),
('390', 'NT (European)', 'NT (European)', 'IUCN Threat listing'),
('391', 'CR (European)', 'CR (European)', 'IUCN Threat listing'),
('392', 'VU (European)', 'VU (European)', 'IUCN Threat listing'),
('393', 'DD (European)', 'DD (European)', 'IUCN Threat listing'),
('394', 'EN (European)', 'EN (European)', 'IUCN Threat listing'),
('395', 'Legal Protection', 'Legal protection', 'Legal listing'),
('396', 'Legal Protection', 'Legal protection', 'Legal listing'),
('397', 'Legal Protection', 'Legal protection', 'Legal listing'),
('398', 'Legal Protection', 'Legal protection', 'Legal listing'),
('399', 'Legal Protection', 'Legal protection', 'Legal listing'),
('400', 'NR (marine)', 'Nationally Rare (marine species)', 'GB Rarity listing'),
('402', 'NS (marine)', 'Nationally Scarce (marine species)', 'GB Rarity listing'),
('404', 'NS', 'Nationally Scarce', 'GB Rarity listing'),
('405', 'RDB 3', '[Rare]', 'GB Rarity listing'),
('406', 'NR', 'Nationally Rare', 'GB Rarity listing'),
('407', 'RDB K', '[Threat]', 'IUCN Threat listing'),
('408', 'RE', 'RE', 'IUCN Threat listing'),
('409', 'RDB 2', '[Threat]', 'IUCN Threat listing'),
('410', 'RDB 1', '[Threat]', 'IUCN Threat listing'),
('411', 'Nb', '[Scarce]', 'GB Rarity listing'),
('412', 'RDB I', '[Threat]', 'IUCN Threat listing'),
('413', 'Na', '[Scarce]', 'GB Rarity listing'),
('414', 'Notable', '[Scarce]', 'GB Rarity listing'),
('417', 'pRDB 3', '[Rare]', 'GB Rarity listing'),
('418', 'pRDB 1', '[Threat]', 'IUCN Threat listing'),
('419', 'pRDB 2', '[Threat]', 'IUCN Threat listing'),
('421', 'LC', 'LC', 'IUCN Threat listing'),
('423', 'DD', 'DD', 'IUCN Threat listing'),
('424', 'VU', 'VU', 'IUCN Threat listing'),
('425', 'NT', 'NT', 'IUCN Threat listing'),
('426', 'EN', 'EN', 'IUCN Threat listing'),
('427', 'CR', 'CR', 'IUCN Threat listing'),
('428', 'pVU', 'pVU', 'IUCN Threat listing'),
('429', 'pLC', 'pLC', 'IUCN Threat listing'),
('430', 'pEN', 'pEN', 'IUCN Threat listing'),
('431', 'pNT', 'pNT', 'IUCN Threat listing'),
('433', 'pDD', 'pDD', 'IUCN Threat listing'),
('435', 'pCR', 'pCR', 'IUCN Threat listing'),
('437', 'RE', 'RE', 'IUCN Threat listing'),
('438', 'CR(PE)', 'CR(PE)', 'IUCN Threat listing'),
('440', '(LR)', '[Threat]', 'IUCN Threat listing'),
('442', 'Section 41 Priority Species - research only', 'S41. Priority Species - research only', 'Legal listing'),
('443', 'Section 41 Priority Species', 'S41. Priority Species', 'Legal listing'),
('471', 'RE', 'RE', 'IUCN Threat listing'),
('472', '[Nb]', '[Scarce]', 'GB Rarity listing'),
('473', '[RDB 1]', '[Threat]', 'IUCN Threat listing'),
('474', 'NA', 'NA', 'IUCN Threat listing'),
('475', '[RDB 2]', '[Threat]', 'IUCN Threat listing'),
('476', '[RDB K]', '[Threat]', 'IUCN Threat listing'),
('477', '[RDB 3]', '[Threat]', 'IUCN Threat listing'),
('478', '[Na]', '[Scarce]', 'GB Rarity listing'),
('479', '[RDB I]', '[Threat]', 'IUCN Threat listing'),
('481', '[NR]', '[Rare]', 'GB Rarity listing'),
('482', '[Extinct]', '[Threat]', 'IUCN Threat listing'),
('483', '[Not assessed]', '[Threat]', 'IUCN Threat listing'),
('485', '[Notable]', '[Scarce]', 'GB Rarity listing'),
('486', '[NS]', '[Scarce]', 'GB Rarity listing'),
('487', 'pNS', 'pNS', 'GB Rarity listing'),
('489', 'NR', 'Nationally Rare', 'GB Rarity listing');